---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /media/ssd/Music:/music:ro
      - /media/ssd/Videos/TV:/tv:ro
      - /media/ssd/Videos/Kids:/kids:ro
      - /media/ssd/Videos/Movies:/movies:ro
      - /media/ssd/Videos/Workout:/workout:ro
      - /media/ssd/Podcasts:/podcasts:ro
      - /media/ssd/Photos:/photos:ro
    ports:
      - 8096:8096
    restart: unless-stopped
