---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/wdmycloud/Music:/music:ro
      - /mnt/wdmycloud/Videos/TV:/tv:ro
      - /mnt/wdmycloud/Videos/Movies:/movies:ro
      - /mnt/wdmycloud/Videos/Workout:/workout:ro
      - /mnt/wdmycloud/Podcasts:/podcasts:ro
      - /mnt/wdmycloud/Photos:/photos:ro
    ports:
      - 8096:8096
    restart: unless-stopped
